apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: application-pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .

  tasks:
  # First task is to clone repo from github into the workspace
  - name: git-clone
    taskRef:
       name: git-clone
    resources:
      - name: git-source
    params:
      - name: git-url
        value: $(params.imageUrl)

  # Second task is to build the image and push it to the registry      
  - name: build-image-from-source
    taskRef:
      name: build-image-from-source
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: git-source
          resource: git-source

  # Third task is to deploy the image to the cluster        
  - name: deploy-application
    taskRef:
      name: deploy-application
    runAfter:
      - build-image-from-source
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: pathToYamlFile
        value: "$(params.pathToYamlFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: git-source
          resource: git-source
