apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-demo
  description: "A pipeline that clones a github repo and runs a build and deploy to openshift cluster"
spec:
  workspaces:
    - name: source
      description: "The source code will be cloned into this workspace"
      mountPath: /workspace/source
  params:
    - name: github-repo-url
      description: "The URL of the github repo to clone"
      default: "https://github.com/pewpewtron/okd-tekton-workshop"
    - name: github-repo-revision
      description: "The revision of the github repo to clone"
      default: "main"
    
  tasks:
  # ⬇️ First task is to clone repo from github into the workspace
  - name: clone-sources
    params:
      - name: github-repo-url
        value: $(params.github-repo-url)
      - name: github-repo-revision
        value: $(params.github-repo-revision)
    taskRef:
       kind: Task
       name: git-clone
    workspaces:
      - name: output
        workspace: source

  # 🔁⬆️ Second task is to build the image and push it to the registry
  - name: build-push-image
    params:
      - name: image
        value: $(params.image) 
      - name: dockerfile
        value: $(params.dockerfile)
      - name: context
        value: $(workspaces.source.path)/$(params.context)/
      - name: build-extra-args
        value: ""
      - name: push-extra-args
        value: ""
    taskRef:
        kind: Task
        name: docker-build
    workspaces:
      - name: output
        workspace: source

  # Third task is to deploy the image to the cluster        
