apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-build-push-image
spec:
  description: "Build and push the image to the registry"
  workspaces:
    - name: source
      description: "The source code will be cloned into this workspace"
      mountPath: /workspace/source
  params:
    - name: pathToDockerfile
      description: "The path to the Dockerfile"
      default: "./Dockerfile"
    - name: dockerio-username
      description: "The username of the dockerio account"
      default: "pewpewtron"
    - name: dockerio-password
      description: "The password of the dockerio account"
      default: "8585d7e9-13d5-4e75-bf9e-7e9679f94721"
    - name: imageUrl
      description: "The name of the image to build"
      default: "pewpewtron/okd-tekton-workshop"
    - name: imageTag
      description: "The tag of the image to build"
      default: "latest"
    - name: pathToContext
      description: "The path to the build context"
      default: ./src
  steps:
    - name: check-source
      image: ubuntu:latest
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        echo $(workspaces.source.path)/$(inputs.params.pathToContext)/$(inputs.params.pathToDockerfile)
        ls -la
        cd $(params.pathToContext)
        ls -la
        pwd
        cat $(workspaces.source.path)/$(inputs.params.pathToContext)/$(inputs.params.pathToDockerfile)

    - name: build-push-image
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - "--context=$(workspace.source.path)/$(inputs.params.pathToContext)"
        - "--dockerfile=$(inputs.params.pathToDockerfile)"
        - "--destination=$(inputs.params.imageUrl):$(inputs.params.imageTag)"
        - "--insecure"
        - "--insecure-pull"
        - "--skip-tls-verify"
        - "--skip-tls-verify-pull"